#!/usr/bin/env bash
# This script displays specific fields from /etc/passwd in a concise format
while IFS=':' read -r user pass uid gid info home shell
do
    echo "$user:$uid:$home"
done < /etc/passwd
