#!/usr/bin/env bash
# Groups visitors by IP and HTTP status code
awk 'NF >= 9 && $9 ~ /^[0-9]+$/ {count[$1" "$9]++} END {for (key in count) print count[key], key}' "${1:-apache-access.log}" | sort -rn
