#!/usr/bin/env bash
# Groups visitors by IP and HTTP status code from an Apache log file
awk '{print $1, $9}' apache-access.log | sort | uniq -c | sort -nr | awk '$2 != "" && $3 != "" {print $1, $2, $3}'
