#!/usr/bin/env bash
# Groups visitors by IP and HTTP status code with clean formatting
awk '{print $1, $9}' apache-access.log | sort | uniq -c | sort -nr | awk 'NF==3 {printf "%s %s %s\n", $1, $2, $3}'
