#!/usr/bin/env bash
# Creates a PID file and handles SIGINT and SIGTERM
PID_FILE="/var/run/myscript.pid"

# PID-i fayla yaz
echo "$$" > "$PID_FILE"

# SIGINT trap
trap 'echo "Y U no love me?!"' SIGINT

# SIGTERM trap
trap 'echo "I hate the kill command"; rm "$PID_FILE"; exit' SIGTERM

# SIGQUIT trap
trap 'rm "$PID_FILE"; exit' SIGQUIT

while true
do
    echo "To infinity and beyond"
    sleep 2
done
